name = "lihui-blog"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "lihui-db"
database_id = "aa5cf546-2dc2-4120-aed0-b3665eed29ec"

[[send_email]]
name = "EMAIL"

[vars]
JWT_SECRET = "l1H2u1_Bl0g_$3cr3t_K3y!2026xZ9qW7pR4vN8jF2hL6tY0dA5cB1eG3kM9"
